from __future__ import annotations

from pawpal_system import Owner, OwnerScheduler, Pet, Task
from ..schemas import Citation, GuidanceItem, RAGScheduleResponse, ScheduledTask, ScheduleRequest


def build_deterministic_fallback(
    request: ScheduleRequest,
    citations_by_pet: dict[str, list[Citation]],
    validation_errors: list[str],
) -> RAGScheduleResponse:
    owner = Owner(name=request.owner_name, available_time_per_day=request.available_time_per_day)
    pets: list[Pet] = []
    tasks_per_pet: dict[str, list[Task]] = {}

    for pet_in in request.pets:
        pet = Pet(
            name=pet_in.name,
            species=pet_in.species,
            age=pet_in.age,
            energy_level=pet_in.energy_level,
            special_needs=list(pet_in.special_needs),
        )
        owner.add_pet(pet)
        pets.append(pet)
        tasks_per_pet[pet.name] = []
        for t in pet_in.tasks:
            tasks_per_pet[pet.name].append(
                Task(
                    title=t.title,
                    duration_minutes=t.duration_minutes,
                    priority=t.priority,
                    frequency=t.frequency,
                    description=t.description,
                    preferred_time=t.preferred_time,
                    completed=t.completed,
                )
            )

    scheduler = OwnerScheduler(owner, pets, tasks_per_pet)
    scheduler.generate_consolidated_schedule()

    schedule_items: list[ScheduledTask] = []
    for day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]:
        summary = scheduler.get_daily_summary(day)
        for pet_name, entries in summary.items():
            for entry in entries:
                task = entry["task"]
                base_citations = citations_by_pet.get(pet_name) or [
                    Citation(record_id="fallback-none", section="system", snippet="No retrieval context found.")
                ]
                schedule_items.append(
                    ScheduledTask(
                        pet=pet_name,
                        day=day,
                        time=entry["time"],
                        title=task.title,
                        duration_minutes=task.duration_minutes,
                        priority=task.priority,
                        reason="Generated by deterministic fallback scheduler after AI validation failure.",
                        citations=base_citations[:1],
                    )
                )

    guidance: list[GuidanceItem] = []
    for pet in request.pets:
        pet_citations = citations_by_pet.get(pet.name) or [
            Citation(record_id="fallback-none", section="system", snippet="No retrieval context found.")
        ]
        guidance.append(
            GuidanceItem(
                title=f"Care guidance for {pet.name}",
                detail="Prioritize high-priority and medication-related tasks first when daily time is limited.",
                citations=pet_citations[:1],
            )
        )

    dropped = []
    for day, entries in scheduler.get_dropped_tasks().items():
        for e in entries:
            dropped.append(
                {
                    "day": day,
                    "pet": e["pet"],
                    "title": e["task"].title,
                    "duration_minutes": e["task"].duration_minutes,
                }
            )

    return RAGScheduleResponse(
        schedule=schedule_items,
        guidance=guidance,
        dropped_tasks=dropped,
        retrieval_context_count=sum(len(v) for v in citations_by_pet.values()),
        model_provider="deterministic-fallback",
        validation_status="fallback",
        validation_errors=validation_errors,
        used_fallback=True,
    )
